import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const prisma = new PrismaClient({
  adapter: new PrismaBetterSqlite3({ url: "file:./dev.db" }),
});

async function main() {
  // 清空已有数据（按外键依赖顺序）
  await prisma.activityLog.deleteMany();
  await prisma.maintenancePlan.deleteMany();
  await prisma.project.deleteMany();
  await prisma.contactSubmission.deleteMany();
  await prisma.case.deleteMany();
  await prisma.template.deleteMany();

  console.log("已清空旧数据");

  // ==================== ContactSubmission ====================
  const submissions = await Promise.all([
    prisma.contactSubmission.create({
      data: {
        company: "星图智能",
        industry: "AI / SaaS",
        contactName: "张明",
        contact: "13800138001",
        package: "Pro",
        timeline: "2 周内",
        reference: "https://example-saas.com",
        description: "AI 写作工具产品官网，需要展示核心功能、使用场景和定价方案",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "睿信财务",
        industry: "企业服务",
        contactName: "李婷",
        contact: "alice@ruixin.com",
        package: "Pro",
        timeline: "1 个月内",
        description: "财务咨询公司官网，需要在线预约功能和案例展示",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "极客学院",
        industry: "教育培训",
        contactName: "王浩",
        contact: "13900139002",
        package: "Pro",
        timeline: "2 周内",
        reference: "https://example-edu.com",
        description: "编程培训课程官网，需要课程展示、讲师介绍和在线报名",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "悦齿口腔",
        industry: "本地服务",
        contactName: "赵丽",
        contact: "13700137003",
        package: "Starter",
        timeline: "越快越好",
        description: "口腔诊所单页官网，需要在线预约和医生团队展示",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "鑫达精密",
        industry: "制造业",
        contactName: "陈工",
        contact: "13600136004",
        package: "Premium",
        timeline: "1 个月内",
        reference: "https://example-mfg.com",
        description: "精密零部件制造企业官网，需要产品展示、资质认证和海外询盘表单",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "云谷科技园",
        industry: "招商展示",
        contactName: "刘总",
        contact: "invest@yungu.com",
        package: "Premium",
        timeline: "2 周内",
        description: "科技园区招商官网，需要园区展示、入驻流程和在线咨询",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "悠然瑜伽",
        industry: "本地服务",
        contactName: "孙教练",
        contact: "13500135005",
        package: "Starter",
        timeline: "1 周内",
        description: "瑜伽馆单页官网，需要课程表、教练介绍和预约入口",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "未来学堂",
        industry: "教育培训",
        contactName: "周老师",
        contact: "hello@futuredu.com",
        package: "Pro",
        timeline: "2 周内",
        description: "K12 在线教育平台官网，需要课程体系展示和试听预约",
        status: "converted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "快闪餐饮",
        industry: "本地服务",
        contactName: "吴经理",
        contact: "13300133006",
        package: "Pro",
        timeline: "越快越好",
        description: "连锁餐饮品牌官网，需要菜单展示、门店信息和加盟咨询",
        status: "qualified",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "星辰创投",
        industry: "企业服务",
        contactName: "郑总",
        contact: "contact@starcap.cn",
        package: "Premium",
        timeline: "暂不确定",
        description: "创投机构官网，需要基金介绍、投资案例和团队展示",
        status: "contacted",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "青苗教育",
        industry: "教育培训",
        contactName: "黄老师",
        contact: "13200132007",
        package: "Starter",
        timeline: "1 个月内",
        description: "少儿英语培训单页官网，需要课程介绍和报名入口",
        status: "new",
      },
    }),
    prisma.contactSubmission.create({
      data: {
        company: "绿野环保",
        industry: "制造业",
        contactName: "林工",
        contact: "info@greenye.com",
        package: "Pro",
        timeline: "2 周内",
        description: "环保设备制造企业官网，需要产品中心、技术方案和合作案例",
        status: "new",
      },
    }),
  ]);

  console.log(`已创建 ${submissions.length} 条联系提交`);

  // ==================== Project ====================
  const projects = await Promise.all([
    prisma.project.create({
      data: {
        title: "星图智能产品官网",
        description: "AI 写作工具产品官网，展示核心功能、使用场景和定价方案",
        packageName: "Pro",
        status: "launched",
        pages: 6,
        revisions: 2,
        revisionUsed: 2,
        price: 18000,
        deadline: new Date("2026-04-15"),
        launchedAt: new Date("2026-04-10"),
        startedAt: new Date("2026-03-28"),
        domain: "startu-ai.com",
        clientName: "星图智能",
        submissionId: submissions[0].id,
      },
    }),
    prisma.project.create({
      data: {
        title: "睿信财务企业官网",
        description: "财务咨询公司官网，包含在线预约和案例展示",
        packageName: "Pro",
        status: "launched",
        pages: 7,
        revisions: 2,
        revisionUsed: 1,
        price: 22000,
        deadline: new Date("2026-04-20"),
        launchedAt: new Date("2026-04-18"),
        startedAt: new Date("2026-04-01"),
        domain: "ruixin-financial.com",
        clientName: "睿信财务",
        submissionId: submissions[1].id,
      },
    }),
    prisma.project.create({
      data: {
        title: "极客学院课程官网",
        description: "编程培训课程官网，课程展示、讲师介绍和在线报名",
        packageName: "Pro",
        status: "maintenance",
        pages: 5,
        revisions: 2,
        revisionUsed: 2,
        price: 15000,
        deadline: new Date("2026-03-30"),
        launchedAt: new Date("2026-03-25"),
        startedAt: new Date("2026-03-12"),
        domain: "geek-academy.cn",
        clientName: "极客学院",
        submissionId: submissions[2].id,
      },
    }),
    prisma.project.create({
      data: {
        title: "悦齿口腔单页官网",
        description: "口腔诊所单页官网，在线预约和医生团队展示",
        packageName: "Starter",
        status: "launched",
        pages: 1,
        revisions: 1,
        revisionUsed: 1,
        price: 5000,
        deadline: new Date("2026-04-05"),
        launchedAt: new Date("2026-04-02"),
        startedAt: new Date("2026-03-28"),
        domain: "yuechi-dental.com",
        clientName: "悦齿口腔",
        submissionId: submissions[3].id,
      },
    }),
    prisma.project.create({
      data: {
        title: "鑫达精密品牌官网",
        description: "精密零部件制造企业官网，产品展示、资质认证和海外询盘",
        packageName: "Premium",
        status: "reviewing",
        pages: 10,
        revisions: 3,
        revisionUsed: 2,
        price: 58000,
        deadline: new Date("2026-05-30"),
        startedAt: new Date("2026-04-10"),
        clientName: "鑫达精密",
        submissionId: submissions[4].id,
      },
    }),
    prisma.project.create({
      data: {
        title: "云谷科技园招商站",
        description: "科技园区招商官网，园区展示、入驻流程和在线咨询",
        packageName: "Premium",
        status: "developing",
        pages: 8,
        revisions: 3,
        revisionUsed: 1,
        price: 65000,
        deadline: new Date("2026-06-15"),
        startedAt: new Date("2026-04-20"),
        clientName: "云谷科技园",
        submissionId: submissions[5].id,
      },
    }),
    prisma.project.create({
      data: {
        title: "悠然瑜伽预约页",
        description: "瑜伽馆单页官网，课程表、教练介绍和预约入口",
        packageName: "Starter",
        status: "launched",
        pages: 1,
        revisions: 1,
        revisionUsed: 1,
        price: 3500,
        deadline: new Date("2026-04-01"),
        launchedAt: new Date("2026-03-28"),
        startedAt: new Date("2026-03-25"),
        domain: "youan-yoga.com",
        clientName: "悠然瑜伽",
        submissionId: submissions[6].id,
      },
    }),
    prisma.project.create({
      data: {
        title: "未来学堂教育平台",
        description: "K12 在线教育平台官网，课程体系展示和试听预约",
        packageName: "Pro",
        status: "designing",
        pages: 6,
        revisions: 2,
        revisionUsed: 0,
        price: 25000,
        deadline: new Date("2026-05-20"),
        startedAt: new Date("2026-04-25"),
        clientName: "未来学堂",
        submissionId: submissions[7].id,
      },
    }),
  ]);

  console.log(`已创建 ${projects.length} 个项目`);

  // ==================== Template ====================
  const templates = await Promise.all([
    prisma.template.create({
      data: {
        name: "SaaS 产品官网模板",
        industry: "AI / SaaS",
        description: "适用于 AI 工具、SaaS 产品的官网模板，包含产品展示、功能介绍、定价方案",
        pages: JSON.stringify(["首页", "功能", "使用场景", "价格", "FAQ", "联系"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "B2B 企业服务模板",
        industry: "企业服务",
        description: "适用于咨询、财务、法律等企业服务公司，包含服务介绍、案例展示、团队介绍",
        pages: JSON.stringify(["首页", "关于", "服务", "解决方案", "案例", "联系"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "教育培训课程模板",
        industry: "教育培训",
        description: "适用于培训机构、在线教育，包含课程展示、师资介绍、报名入口",
        pages: JSON.stringify(["首页", "课程", "师资", "成果", "报名", "常见问题"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "本地服务门店模板",
        industry: "本地服务",
        description: "适用于口腔、美容、健身等本地服务门店，包含服务项目、门店信息、预约",
        pages: JSON.stringify(["首页", "服务项目", "关于", "门店信息", "预约"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "制造业品牌模板",
        industry: "制造业",
        description: "适用于制造企业、工厂，包含产品中心、资质认证、合作案例",
        pages: JSON.stringify(["首页", "产品", "关于", "资质", "合作", "联系"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "招商展示模板",
        industry: "招商展示",
        description: "适用于园区招商、品牌加盟，包含项目亮点、合作模式、在线咨询",
        pages: JSON.stringify(["首页", "项目亮点", "合作模式", "资料下载", "联系"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "医疗健康模板",
        industry: "医疗健康",
        description: "适用于中医馆、诊所、健康中心，包含医生团队、科室介绍、在线预约",
        pages: JSON.stringify(["首页", "科室介绍", "医生团队", "诊疗项目", "在线预约", "患者评价"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "电商品牌模板",
        industry: "电商零售",
        description: "适用于生鲜电商、品牌官网，包含产品展示、门店网络、加盟合作",
        pages: JSON.stringify(["首页", "产品中心", "门店网络", "品质保障", "加盟合作", "联系我们"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "房产楼盘模板",
        industry: "房产地产",
        description: "适用于高端住宅、商业地产，包含楼盘展示、3D看房、在线咨询",
        pages: JSON.stringify(["首页", "项目概览", "户型鉴赏", "3D样板间", "周边配套", "在线预约"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "餐饮连锁模板",
        industry: "餐饮美食",
        description: "适用于连锁餐饮、特色美食，包含菜品展示、门店查询、加盟招商",
        pages: JSON.stringify(["首页", "品牌故事", "特色菜品", "门店查询", "加盟合作", "联系我们"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "法律服务模板",
        industry: "法律服务",
        description: "适用于律所、法律咨询，包含律师团队、服务领域、在线咨询",
        pages: JSON.stringify(["首页", "关于我们", "服务领域", "律师团队", "成功案例", "在线咨询"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "健身运动模板",
        industry: "健身运动",
        description: "适用于健身房、瑜伽馆，包含课程展示、教练团队、会员预约",
        pages: JSON.stringify(["首页", "课程体系", "教练团队", "门店查询", "会员服务", "在线预约"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "创意设计模板",
        industry: "创意设计",
        description: "适用于摄影工作室、设计公司，包含作品展示、服务介绍、在线预约",
        pages: JSON.stringify(["首页", "作品集", "服务项目", "合作流程", "在线预约", "联系我们"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "公益组织模板",
        industry: "公益组织",
        description: "适用于基金会、公益项目，包含项目展示、捐赠入口、志愿者招募",
        pages: JSON.stringify(["首页", "关于我们", "公益项目", "项目成果", "捐赠支持", "志愿者招募"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "宠物服务模板",
        industry: "宠物服务",
        description: "适用于宠物医院、宠物美容，包含服务展示、门店环境、在线预约",
        pages: JSON.stringify(["首页", "服务项目", "门店环境", "医生团队", "会员服务", "在线预约"]),
      },
    }),
    prisma.template.create({
      data: {
        name: "汽车服务模板",
        industry: "汽车服务",
        description: "适用于汽车养护、4S店，包含服务展示、门店查询、在线预约",
        pages: JSON.stringify(["首页", "服务项目", "门店查询", "品质保障", "会员服务", "在线预约"]),
      },
    }),
  ]);

  console.log(`已创建 ${templates.length} 个模板`);

  // ==================== MaintenancePlan ====================
  const maintenancePlans = await Promise.all([
    prisma.maintenancePlan.create({
      data: {
        name: "增强维护",
        price: 2999,
        period: "monthly",
        features: JSON.stringify(["托管与 SSL", "月度访问报告", "性能检查", "内容更新（5页内）", "维护建议"]),
        projectId: projects[2].id, // 极客学院
      },
    }),
    prisma.maintenancePlan.create({
      data: {
        name: "基础维护",
        price: 699,
        period: "monthly",
        features: JSON.stringify(["托管与 SSL", "备份", "小文案修改", "表单检查"]),
        projectId: projects[0].id, // 星图智能
      },
    }),
    prisma.maintenancePlan.create({
      data: {
        name: "增强维护",
        price: 3499,
        period: "monthly",
        features: JSON.stringify(["托管与 SSL", "月度访问报告", "性能检查", "内容更新（8页内）", "维护建议", "数据分析"]),
        projectId: projects[1].id, // 睿信财务
      },
    }),
    prisma.maintenancePlan.create({
      data: {
        name: "基础维护",
        price: 499,
        period: "monthly",
        features: JSON.stringify(["托管与 SSL", "备份", "小文案修改"]),
        projectId: projects[3].id, // 悦齿口腔
      },
    }),
    prisma.maintenancePlan.create({
      data: {
        name: "基础维护",
        price: 499,
        period: "monthly",
        features: JSON.stringify(["托管与 SSL", "备份", "小文案修改"]),
        projectId: projects[6].id, // 悠然瑜伽
      },
    }),
  ]);

  console.log(`已创建 ${maintenancePlans.length} 个维护计划`);

  // ==================== Case ====================
  const cases = await Promise.all([
    prisma.case.create({
      data: {
        slug: "aigc-saas-launch",
        title: "星图智能：AI 写作工具产品官网上线",
        industry: "AI / SaaS",
        tags: JSON.stringify(["产品官网", "响应式", "SEO", "定价页"]),
        clientName: "星图智能",
        background: "星图智能是一款 AI 驱动的写作辅助工具，面向内容创作者和营销团队。产品已进入公测阶段，需要一个专业的官网来展示产品功能、收集用户注册。",
        challenge: "作为一家初创公司，需要在 2 周内上线一个能够展示产品价值、支持用户注册的官网。团队没有专门的设计和前端开发资源，同时需要确保官网在移动端有良好的体验。",
        solution: "采用 Pro 套餐，使用 SaaS 产品官网模板快速搭建。首页聚焦产品核心价值，功能页详细展示 AI 写作的各个模块，定价页清晰呈现三档方案。整体设计简洁现代，突出科技感。",
        result: "10 天内完成从设计到上线的全流程。官网上线后首月获得 2000+ 访问量，试用注册转化率达到 8.5%，较之前的落地页提升了 3 倍。",
        pages: JSON.stringify(["首页", "功能介绍", "使用场景", "定价方案", "常见问题", "联系我们"]),
        packageName: "Pro",
        timeline: "10 天",
        testimonial: "从提交需求到官网上线只用了 10 天，效果超出预期。特别是定价页的设计，帮助我们清晰传达了产品价值。",
        testimonialAuthor: "张明，星图智能 CEO",
        featured: true,
        sortOrder: 1,
        designConfig: JSON.stringify({
          style: "stripe",
          primary: "#635BFF",
          secondary: "#0A2540",
          accent: "#00D4AA",
          background: "#0A2540",
          surface: "#1A1A2E",
          text: "#FFFFFF",
          muted: "#8892B0",
          gradient: "linear-gradient(135deg, #635BFF 0%, #00D4AA 100%)",
          fontDisplay: "'Inter', sans-serif",
          fontBody: "'Inter', sans-serif",
          borderRadius: "12px",
          heroStyle: "gradient-mesh",
          cardStyle: "glass-dark",
        }),
        images: JSON.stringify({
          hero: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=600&fit=crop",
          gallery: [
            "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop",
            "https://images.unsplash.com/photo-1684163761883-8c4d591c1b60?w=600&h=400&fit=crop",
            "https://images.unsplash.com/photo-1707161258171-8b0fd12c0a94?w=600&h=400&fit=crop",
            "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&h=400&fit=crop",
          ],
        }),
      },
    }),
    prisma.case.create({
      data: {
        slug: "fintech-advisor",
        title: "睿信财务：专业咨询服务官网升级",
        industry: "企业服务",
        tags: JSON.stringify(["企业官网", "在线预约", "案例展示", "响应式"]),
        clientName: "睿信财务",
        background: "睿信财务是一家提供企业财务咨询和税务筹划服务的公司，服务对象为中小企业。原有的官网设计陈旧，无法有效展示专业能力和案例成果。",
        challenge: "需要一个能够体现专业形象的官网，同时支持客户在线预约咨询服务。官网需要展示服务案例、团队资质，并且要符合金融行业的合规要求。",
        solution: "采用 Pro 套餐，设计风格偏稳重专业。首页突出品牌定位和核心服务，案例页展示成功项目，团队页详细介绍顾问资质。集成在线预约表单，支持客户自助预约。",
        result: "12 天完成交付。新官网上线后，月均咨询预约量从 5 个增长到 18 个，增长 260%。客户反馈官网提升了品牌信任度。",
        pages: JSON.stringify(["首页", "关于我们", "服务项目", "成功案例", "团队介绍", "在线咨询", "联系我们"]),
        packageName: "Pro",
        timeline: "12 天",
        testimonial: "新官网帮助我们建立了更专业的线上形象，客户预约量明显增加。修改反馈也很高效，2 轮就达到了满意效果。",
        testimonialAuthor: "李婷，睿信财务市场总监",
        featured: true,
        sortOrder: 2,
        designConfig: JSON.stringify({
          style: "corporate",
          primary: "#1E3A5F",
          secondary: "#C9A227",
          accent: "#2E86AB",
          background: "#F8F9FA",
          surface: "#FFFFFF",
          text: "#1E3A5F",
          muted: "#6C757D",
          gradient: "linear-gradient(135deg, #1E3A5F 0%, #2E86AB 100%)",
          fontDisplay: "'Georgia', serif",
          fontBody: "'Helvetica Neue', sans-serif",
          borderRadius: "8px",
          heroStyle: "split-layout",
          cardStyle: "bordered",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&h=400&fit=crop"]}),
      },
    }),
    prisma.case.create({
      data: {
        slug: "coding-bootcamp",
        title: "极客学院：编程培训课程官网",
        industry: "教育培训",
        tags: JSON.stringify(["课程展示", "在线报名", "讲师介绍", "响应式"]),
        clientName: "极客学院",
        background: "极客学院是一家专注编程技能培训的机构，提供 Python、前端、数据分析等课程。需要一个能够展示课程体系、讲师团队，并支持在线报名的官网。",
        challenge: "课程内容丰富，需要清晰的层级展示。同时需要支持课程试听预约和正式报名两个转化路径。移动端流量占比超过 60%，需要优秀的移动端体验。",
        solution: "采用 Pro 套餐，首页用数据和学员成果建立信任。课程页按方向分类展示，每门课程有详细的课程大纲和讲师介绍。报名流程简化为 3 步，降低转化门槛。",
        result: "9 天完成交付。官网上线后课程咨询量提升 150%，在线报名转化率从 3% 提升到 12%。学员反馈官网体验流畅，信息清晰。",
        pages: JSON.stringify(["首页", "课程体系", "讲师团队", "学员成果", "在线报名", "常见问题"]),
        packageName: "Pro",
        timeline: "9 天",
        testimonial: "官网很好地展示了我们的课程体系和教学质量，报名转化率比之前提升了很多。",
        testimonialAuthor: "王浩，极客学院创始人",
        featured: true,
        sortOrder: 3,
        designConfig: JSON.stringify({
          style: "vercel",
          primary: "#000000",
          secondary: "#7928CA",
          accent: "#FF0080",
          background: "#000000",
          surface: "#111111",
          text: "#FFFFFF",
          muted: "#888888",
          gradient: "linear-gradient(135deg, #7928CA 0%, #FF0080 100%)",
          fontDisplay: "'SF Mono', monospace",
          fontBody: "'Inter', sans-serif",
          borderRadius: "0px",
          heroStyle: "terminal",
          cardStyle: "minimal-dark",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1515879218367-8466d910auj2?w=600&h=400&fit=crop"]}),
      },
    }),
    prisma.case.create({
      data: {
        slug: "dental-clinic",
        title: "悦齿口腔：单页预约官网",
        industry: "本地服务",
        tags: JSON.stringify(["单页官网", "在线预约", "医生展示", "移动端"]),
        clientName: "悦齿口腔",
        background: "悦齿口腔是一家社区口腔诊所，主要服务周边居民。之前没有官网，客户主要靠口碑和线下引流。希望通过官网建立线上存在感，支持在线预约。",
        challenge: "预算有限，需要在控制成本的同时建立专业的线上形象。核心需求是在线预约功能，让客户可以方便地选择医生和时间段。",
        solution: "采用 Starter 套餐，单页设计聚焦核心信息。页面包含医生团队、服务项目、诊所环境和在线预约入口。设计风格温馨专业，消除看牙的心理距离感。",
        result: "5 天快速上线。官网上线后月均在线预约量从 0 增长到 35 次，新客到店率提升 40%。成为周边社区口碑传播的重要渠道。",
        pages: JSON.stringify(["首页（包含医生团队、服务项目、诊所环境、在线预约）"]),
        packageName: "Starter",
        timeline: "5 天",
        testimonial: "5 天就上线了，效果很好。现在大部分新客户都是通过官网预约来的。",
        testimonialAuthor: "赵丽，悦齿口腔负责人",
        featured: false,
        sortOrder: 4,
        designConfig: JSON.stringify({
          style: "clean-medical",
          primary: "#00A3E0",
          secondary: "#4ECDC4",
          accent: "#FF6B6B",
          background: "#FFFFFF",
          surface: "#F7FAFA",
          text: "#2D3436",
          muted: "#636E72",
          gradient: "linear-gradient(135deg, #00A3E0 0%, #4ECDC4 100%)",
          fontDisplay: "'Nunito', sans-serif",
          fontBody: "'Open Sans', sans-serif",
          borderRadius: "20px",
          heroStyle: "wave-divider",
          cardStyle: "soft-shadow",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=600&h=400&fit=crop"]}),
      },
    }),
    prisma.case.create({
      data: {
        slug: "manufacturing-b2b",
        title: "鑫达精密：制造业品牌官网",
        industry: "制造业",
        tags: JSON.stringify(["品牌官网", "产品展示", "多语言", "海外询盘"]),
        clientName: "鑫达精密",
        background: "鑫达精密是一家专注精密零部件制造的企业，产品远销海外。需要一个能够展示制造实力、产品线和资质认证的国际化官网，重点服务海外客户。",
        challenge: "产品线丰富，需要清晰的分类展示。海外客户占比高，需要中英文双语支持。同时需要专业的询盘表单，方便海外客户发起合作咨询。",
        solution: "采用 Premium 套餐，打造国际化的品牌形象。首页展示企业实力和核心优势，产品中心按类别详细展示，资质认证区增强信任。中英文双语切换，询盘表单支持多语言。",
        result: "20 天完成交付。官网上线后海外询盘量月均增长 80%，成功签约 3 个海外客户。官网成为参加海外展会时的重要展示工具。",
        pages: JSON.stringify(["首页", "关于我们", "产品中心", "技术实力", "质量认证", "合作案例", "新闻中心", "人才招聘", "联系我们", "English"]),
        packageName: "Premium",
        timeline: "20 天",
        testimonial: "Premium 套餐物有所值，官网的专业度让海外客户对我们更有信心。多语言支持和询盘表单设计得很实用。",
        testimonialAuthor: "陈工，鑫达精密外贸部经理",
        featured: true,
        sortOrder: 5,
        designConfig: JSON.stringify({
          style: "industrial",
          primary: "#1A1A1A",
          secondary: "#B8860B",
          accent: "#E63946",
          background: "#F5F5F5",
          surface: "#FFFFFF",
          text: "#1A1A1A",
          muted: "#666666",
          gradient: "linear-gradient(135deg, #1A1A1A 0%, #B8860B 100%)",
          fontDisplay: "'Roboto Condensed', sans-serif",
          fontBody: "'Roboto', sans-serif",
          borderRadius: "4px",
          heroStyle: "full-width-image",
          cardStyle: "industrial-grid",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1565043666747-69f6646db940?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=600&h=400&fit=crop"]}),
      },
    }),
    prisma.case.create({
      data: {
        slug: "real-estate-dev",
        title: "云谷科技园：招商展示官网",
        industry: "招商展示",
        tags: JSON.stringify(["招商官网", "园区展示", "在线咨询", "3D展示"]),
        clientName: "云谷科技园",
        background: "云谷科技园是一个新兴的科技产业园区，需要一个高品质的招商官网来展示园区环境、入驻优势和合作模式，吸引优质企业入驻。",
        challenge: "招商官网需要传递高端、专业的形象，同时清晰展示园区的地理位置、配套设施和入驻政策。需要支持在线咨询和资料下载功能。",
        solution: "采用 Premium 套餐，打造沉浸式的园区展示体验。首页用大图和数据展示园区实力，虚拟导览展示园区环境，入驻流程清晰明了。集成在线咨询和资料下载功能。",
        result: "18 天完成交付。官网上线后月均入驻咨询量提升 120%，成功签约 5 家企业入驻。官网成为招商团队的核心展示工具。",
        pages: JSON.stringify(["首页", "园区概览", "虚拟导览", "入驻优势", "合作模式", "已入驻企业", "资料下载", "联系我们"]),
        packageName: "Premium",
        timeline: "18 天",
        testimonial: "官网的品质超出了我们的预期，虚拟导览功能特别加分。招商团队现在都用这个官网来给客户做介绍。",
        testimonialAuthor: "刘总，云谷科技园招商总监",
        featured: true,
        sortOrder: 6,
        designConfig: JSON.stringify({
          style: "luxury",
          primary: "#1B4332",
          secondary: "#D4AF37",
          accent: "#2D6A4F",
          background: "#F8F6F0",
          surface: "#FFFFFF",
          text: "#1B4332",
          muted: "#52796F",
          gradient: "linear-gradient(135deg, #1B4332 0%, #D4AF37 100%)",
          fontDisplay: "'Playfair Display', serif",
          fontBody: "'Lato', sans-serif",
          borderRadius: "16px",
          heroStyle: "parallax-image",
          cardStyle: "elegant-border",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&h=400&fit=crop"]}),
      },
    }),
    prisma.case.create({
      data: {
        slug: "yoga-studio",
        title: "悠然瑜伽：预约体验页",
        industry: "本地服务",
        tags: JSON.stringify(["单页预约", "课程表", "移动端", "快速上线"]),
        clientName: "悠然瑜伽",
        background: "悠然瑜伽是一家社区瑜伽馆，主打身心平衡的生活方式。之前通过微信群发布课程信息，希望有一个专业的预约入口和课程展示页面。",
        challenge: "预算有限，需要快速上线。核心需求是展示课程表和教练信息，支持在线预约体验课。风格需要符合瑜伽的宁静、自然氛围。",
        solution: "采用 Starter 套餐，单页设计聚焦预约转化。页面顶部是品牌理念，中间是课程表和教练介绍，底部是预约入口。设计风格自然清新，符合品牌调性。",
        result: "4 天极速上线。新客到店率提升 60%，体验课预约量增长 200%。官网成为小红书种草后的第一转化入口。",
        pages: JSON.stringify(["首页（包含品牌理念、课程表、教练团队、在线预约）"]),
        packageName: "Starter",
        timeline: "4 天",
        testimonial: "4 天就搞定了，比我预期快很多。现在预约体验课方便多了，新客户也多了。",
        testimonialAuthor: "孙教练，悠然瑜伽创始人",
        featured: false,
        sortOrder: 7,
        designConfig: JSON.stringify({
          style: "organic",
          primary: "#8FBC8F",
          secondary: "#DEB887",
          accent: "#CD853F",
          background: "#FAF0E6",
          surface: "#FFFFFF",
          text: "#2F4F4F",
          muted: "#8B8682",
          gradient: "linear-gradient(135deg, #8FBC8F 0%, #DEB887 100%)",
          fontDisplay: "'Cormorant Garamond', serif",
          fontBody: "'Source Sans Pro', sans-serif",
          borderRadius: "24px",
          heroStyle: "nature-overlay",
          cardStyle: "soft-organic",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600&h=400&fit=crop"]}),
      },
    }),
    prisma.case.create({
      data: {
        slug: "edtech-platform",
        title: "未来学堂：在线教育平台官网",
        industry: "教育培训",
        tags: JSON.stringify(["教育平台", "课程体系", "试听预约", "响应式"]),
        clientName: "未来学堂",
        background: "未来学堂是一家 K12 在线教育平台，提供数学、英语、编程等课程。需要一个能够展示课程体系、教学成果，并支持试听预约的官网。",
        challenge: "课程体系复杂，需要清晰的层级展示。目标用户是家长，需要建立信任感。同时需要支持课程试听和正式报名两个转化路径。",
        solution: "采用 Pro 套餐，首页用数据和家长口碑建立信任。课程页按年级和学科分类展示，每门课程有详细的课程介绍和试听入口。家长见证区展示真实反馈。",
        result: "11 天完成交付。官网上线后试听预约量月均增长 180%，正式报名转化率从 5% 提升到 15%。家长反馈官网信息清晰，预约方便。",
        pages: JSON.stringify(["首页", "课程体系", "教学特色", "家长见证", "师资团队", "试听预约"]),
        packageName: "Pro",
        timeline: "11 天",
        testimonial: "官网很好地展示了我们的教学理念和课程体系，家长反馈很好。特别是试听预约功能，简化了转化流程。",
        testimonialAuthor: "周老师，未来学堂教学总监",
        featured: false,
        sortOrder: 8,
        designConfig: JSON.stringify({
          style: "playful",
          primary: "#FF6B35",
          secondary: "#004E89",
          accent: "#FCBF49",
          background: "#FFFFFF",
          surface: "#FFF8F0",
          text: "#1A1A2E",
          muted: "#6B7280",
          gradient: "linear-gradient(135deg, #FF6B35 0%, #FCBF49 100%)",
          fontDisplay: "'Poppins', sans-serif",
          fontBody: "'Nunito', sans-serif",
          borderRadius: "16px",
          heroStyle: "bento-grid",
          cardStyle: "colorful-cards",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：医疗健康 ====================
    prisma.case.create({
      data: {
        slug: "medical-clinic",
        title: "仁和中医馆：中医诊疗服务官网",
        industry: "医疗健康",
        tags: JSON.stringify(["中医诊疗", "在线预约", "医生团队", "科室展示"]),
        clientName: "仁和中医馆",
        background: "仁和中医馆是一家集中医诊疗、养生保健为一体的连锁中医馆，拥有 10 位省级名中医。需要一个能够展示中医文化底蕴、医生资质，并支持在线预约的官网。",
        challenge: "中医行业需要传递专业、可信赖的形象，同时要体现传统文化底蕴。医生团队介绍需要突出资质和擅长领域。预约系统需要支持按科室和医生筛选。",
        solution: "采用 Pro 套餐，设计风格融合中医传统元素与现代简约。首页展示品牌理念和名医风采，科室页详细介绍各诊疗方向，医生页展示资质和患者评价。预约系统支持按科室、医生、时间段筛选。",
        result: "14 天完成交付。官网上线后月均在线预约量增长 220%，新客到店率提升 55%。官网成为中医馆品牌传播的核心渠道。",
        pages: JSON.stringify(["首页", "关于我们", "科室介绍", "名医团队", "诊疗项目", "在线预约", "患者评价", "联系我们"]),
        packageName: "Pro",
        timeline: "14 天",
        testimonial: "官网很好地传递了我们的中医文化理念，预约系统非常方便。现在大部分新客户都是通过官网了解并预约的。",
        testimonialAuthor: "王院长，仁和中医馆馆长",
        featured: true,
        sortOrder: 9,
        designConfig: JSON.stringify({
          style: "traditional",
          primary: "#8B0000",
          secondary: "#D4AF37",
          accent: "#228B22",
          background: "#FFF8DC",
          surface: "#FFFEF7",
          text: "#2F1B14",
          muted: "#8B7355",
          gradient: "linear-gradient(135deg, #8B0000 0%, #D4AF37 100%)",
          fontDisplay: "'Noto Serif SC', serif",
          fontBody: "'Noto Sans SC', sans-serif",
          borderRadius: "8px",
          heroStyle: "cultural-overlay",
          cardStyle: "traditional-border",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1551190822-a9ce113ac100?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：电商零售 ====================
    prisma.case.create({
      data: {
        slug: "ecommerce-brand",
        title: "鲜果时光：生鲜电商品牌官网",
        industry: "电商零售",
        tags: JSON.stringify(["品牌官网", "产品展示", "加盟招商", "响应式"]),
        clientName: "鲜果时光",
        background: "鲜果时光是一家主打新鲜水果配送的连锁品牌，拥有 50+ 门店。需要一个品牌官网来展示产品品质、门店网络，并支持加盟咨询。",
        challenge: "生鲜行业需要突出新鲜、健康的品牌形象。产品更新频繁，需要易于维护的内容管理系统。同时需要支持加盟招商和门店查询功能。",
        solution: "采用 Pro 套餐，设计风格清新自然，突出水果的新鲜感。首页用大图展示产品品质，产品页按品类分类展示，门店页支持地图查询。加盟专区展示合作模式和成功案例。",
        result: "12 天完成交付。官网上线后品牌搜索量提升 180%，月均加盟咨询量增长 300%。官网成为品牌形象展示的重要窗口。",
        pages: JSON.stringify(["首页", "产品中心", "门店网络", "品质保障", "加盟合作", "关于我们", "联系方式"]),
        packageName: "Pro",
        timeline: "12 天",
        testimonial: "官网的设计风格完全符合我们的品牌调性，加盟咨询量增长很明显。内容更新也很方便，运营团队自己就能操作。",
        testimonialAuthor: "吴经理，鲜果时光品牌总监",
        featured: true,
        sortOrder: 10,
        designConfig: JSON.stringify({
          style: "fresh",
          primary: "#2ECC71",
          secondary: "#E74C3C",
          accent: "#F39C12",
          background: "#FFFFFF",
          surface: "#F0FFF4",
          text: "#27AE60",
          muted: "#7F8C8D",
          gradient: "linear-gradient(135deg, #2ECC71 0%, #F39C12 100%)",
          fontDisplay: "'Quicksand', sans-serif",
          fontBody: "'Open Sans', sans-serif",
          borderRadius: "20px",
          heroStyle: "product-showcase",
          cardStyle: "fresh-cards",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：房产地产 ====================
    prisma.case.create({
      data: {
        slug: "real-estate-luxury",
        title: "御景华庭：高端住宅项目官网",
        industry: "房产地产",
        tags: JSON.stringify(["楼盘展示", "3D看房", "在线咨询", "品牌视觉"]),
        clientName: "御景华庭",
        background: "御景华庭是一个高端住宅项目，主打城市核心地段的精装大平层。需要一个能够传递高端品质感、展示项目细节，并支持在线预约看房的官网。",
        challenge: "高端楼盘需要极致的视觉呈现，传递品质感和稀缺性。需要支持 3D 样板间展示、户型图查看、在线咨询预约等功能。目标客户群体对审美要求极高。",
        solution: "采用 Premium 套餐，打造沉浸式的楼盘展示体验。首页用全屏视频和精美大图营造品质感，户型页支持 3D 样板间浏览，配套页展示周边生活配套。集成在线预约看房和顾问咨询功能。",
        result: "21 天完成交付。官网上线后月均预约看房量增长 250%，项目到访率提升 80%。官网成为销售团队的核心展示工具。",
        pages: JSON.stringify(["首页", "项目概览", "户型鉴赏", "3D 样板间", "周边配套", "品牌实力", "在线预约", "联系我们"]),
        packageName: "Premium",
        timeline: "21 天",
        testimonial: "官网的视觉效果完全超出了我们的预期，3D 看房功能特别受客户欢迎。销售团队反馈客户到访率明显提升。",
        testimonialAuthor: "刘总，御景华庭营销总监",
        featured: true,
        sortOrder: 11,
        designConfig: JSON.stringify({
          style: "tesla",
          primary: "#000000",
          secondary: "#C0C0C0",
          accent: "#E31937",
          background: "#000000",
          surface: "#111111",
          text: "#FFFFFF",
          muted: "#888888",
          gradient: "linear-gradient(135deg, #000000 0%, #333333 100%)",
          fontDisplay: "'Helvetica Neue', sans-serif",
          fontBody: "'Helvetica Neue', sans-serif",
          borderRadius: "0px",
          heroStyle: "full-screen-video",
          cardStyle: "minimal-dark",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：餐饮美食 ====================
    prisma.case.create({
      data: {
        slug: "restaurant-chain",
        title: "蜀香阁：川菜连锁品牌官网",
        industry: "餐饮美食",
        tags: JSON.stringify(["品牌官网", "菜单展示", "门店查询", "加盟招商"]),
        clientName: "蜀香阁",
        background: "蜀香阁是一家主打正宗川菜的连锁餐饮品牌，拥有 30+ 门店。需要一个能够展示品牌文化、菜品特色，并支持门店查询和加盟咨询的官网。",
        challenge: "餐饮品牌需要突出美食的视觉诱惑力，同时要支持多门店信息展示。菜品更新频繁，需要易于维护。加盟招商是重要的业务拓展渠道。",
        solution: "采用 Pro 套餐，设计风格热情奔放，突出川菜的麻辣鲜香。首页用美食大图吸引眼球，菜品页按类别详细展示，门店页支持地图和列表查询。加盟专区展示合作模式和投资回报。",
        result: "10 天完成交付。官网上线后品牌搜索量提升 150%，月均加盟咨询量增长 200%。官网成为品牌传播和招商的重要渠道。",
        pages: JSON.stringify(["首页", "品牌故事", "特色菜品", "门店查询", "加盟合作", "新闻中心", "联系我们"]),
        packageName: "Pro",
        timeline: "10 天",
        testimonial: "官网的设计风格完全符合我们的品牌调性，菜品展示效果很好。加盟咨询量增长很明显，ROI 很高。",
        testimonialAuthor: "张总，蜀香阁运营总监",
        featured: false,
        sortOrder: 12,
        designConfig: JSON.stringify({
          style: "warm-food",
          primary: "#B91C1C",
          secondary: "#F97316",
          accent: "#DC2626",
          background: "#FFF7ED",
          surface: "#FFFFFF",
          text: "#1C1917",
          muted: "#78716C",
          gradient: "linear-gradient(135deg, #FED7AA 0%, #FECACA 50%, #FCA5A5 100%)",
          fontDisplay: "'Noto Serif SC', 'SimSun', serif",
          fontBody: "'Noto Sans SC', 'PingFang SC', sans-serif",
          borderRadius: "16px",
          heroStyle: "warm-gradient",
          cardStyle: "warm-food",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：法律服务 ====================
    prisma.case.create({
      data: {
        slug: "law-firm",
        title: "正衡律师事务所：专业法律服务官网",
        industry: "法律服务",
        tags: JSON.stringify(["律所官网", "律师团队", "服务领域", "在线咨询"]),
        clientName: "正衡律师事务所",
        background: "正衡律师事务所是一家综合性律所，专注于商事诉讼、知识产权和公司法务。需要一个能够体现专业权威、展示律师资质，并支持在线咨询的官网。",
        challenge: "法律服务需要传递专业、严谨、可信赖的形象。律师团队介绍需要突出专业背景和成功案例。需要支持按服务领域和律师专长进行筛选咨询。",
        solution: "采用 Pro 套餐，设计风格稳重大气，体现法律行业的专业性。首页展示律所实力和核心优势，律师页详细介绍资质和专长，服务页按领域分类展示。在线咨询支持按领域和律师筛选。",
        result: "13 天完成交付。官网上线后月均在线咨询量增长 180%，成功签约 8 个企业法务客户。官网成为律所品牌建设的重要支撑。",
        pages: JSON.stringify(["首页", "关于我们", "服务领域", "律师团队", "成功案例", "新闻资讯", "在线咨询", "联系我们"]),
        packageName: "Pro",
        timeline: "13 天",
        testimonial: "官网的专业度得到了客户的一致好评，咨询量增长明显。特别是律师团队的展示，帮助客户快速找到合适的律师。",
        testimonialAuthor: "陈主任，正衡律师事务所管理合伙人",
        featured: false,
        sortOrder: 13,
        designConfig: JSON.stringify({
          style: "authoritative",
          primary: "#1E3A5F",
          secondary: "#C5A55A",
          accent: "#2563EB",
          background: "#F8FAFC",
          surface: "#FFFFFF",
          text: "#0F172A",
          muted: "#64748B",
          gradient: "linear-gradient(135deg, #1E3A5F 0%, #2D4A6F 50%, #3B5998 100%)",
          fontDisplay: "'Noto Serif SC', 'SimSun', serif",
          fontBody: "'Noto Sans SC', 'PingFang SC', sans-serif",
          borderRadius: "8px",
          heroStyle: "formal-header",
          cardStyle: "formal-bordered",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1479142506502-19b3a3b7ff33?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：健身运动 ====================
    prisma.case.create({
      data: {
        slug: "gym-fitness",
        title: "力行健身：连锁健身品牌官网",
        industry: "健身运动",
        tags: JSON.stringify(["健身品牌", "课程展示", "会员预约", "门店查询"]),
        clientName: "力行健身",
        background: "力行健身是一家连锁健身品牌，拥有 20+ 门店，主打团课和私教服务。需要一个能够展示课程特色、教练团队，并支持会员预约和门店查询的官网。",
        challenge: "健身品牌需要传递活力、专业的形象，同时要支持多门店信息展示。课程种类丰富，需要清晰的分类展示。预约系统需要支持按门店、课程、教练筛选。",
        solution: "采用 Pro 套餐，设计风格活力动感，突出健身的激情。首页用视频和数据展示品牌实力，课程页按类别详细展示，教练页介绍资质和专长。预约系统支持多维度筛选。",
        result: "11 天完成交付。官网上线后月均会员预约量增长 200%，新客到店率提升 70%。官网成为品牌传播和获客的重要渠道。",
        pages: JSON.stringify(["首页", "课程体系", "教练团队", "门店查询", "会员服务", "关于我们", "联系方式"]),
        packageName: "Pro",
        timeline: "11 天",
        testimonial: "官网的设计风格很有活力，完全符合健身品牌的调性。预约系统很方便，会员反馈很好。",
        testimonialAuthor: "李教练，力行健身品牌经理",
        featured: false,
        sortOrder: 14,
        designConfig: JSON.stringify({
          style: "energetic",
          primary: "#DC2626",
          secondary: "#F59E0B",
          accent: "#EF4444",
          background: "#0F0F0F",
          surface: "#1A1A1A",
          text: "#FFFFFF",
          muted: "#A3A3A3",
          gradient: "linear-gradient(135deg, #EF4444 0%, #F97316 50%, #FBBF24 100%)",
          fontDisplay: "'Oswald', 'Bebas Neue', sans-serif",
          fontBody: "'Inter', 'Noto Sans SC', sans-serif",
          borderRadius: "12px",
          heroStyle: "full-bleed-dark",
          cardStyle: "dark-accent",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：摄影工作室 ====================
    prisma.case.create({
      data: {
        slug: "photo-studio",
        title: "光影视界：商业摄影工作室官网",
        industry: "创意设计",
        tags: JSON.stringify(["作品展示", "服务介绍", "在线预约", "视觉设计"]),
        clientName: "光影视界",
        background: "光影视界是一家专注于商业摄影和视频制作的工作室，服务品牌广告、电商产品、婚礼纪实等领域。需要一个能够展示作品质量、服务流程，并支持在线预约的官网。",
        challenge: "摄影工作室需要极致的视觉呈现，作品展示需要支持高清大图和视频。服务流程需要清晰明了，方便客户了解合作方式。预约系统需要支持按服务类型和时间段筛选。",
        solution: "采用 Pro 套餐，设计风格简约大气，突出作品的视觉冲击力。首页用作品轮播展示实力，作品页按类别分类展示，服务页详细介绍流程和报价。预约系统支持在线沟通和档期查询。",
        result: "10 天完成交付。官网上线后月均咨询量增长 250%，成功签约 12 个商业项目。官网成为工作室品牌建设的核心工具。",
        pages: JSON.stringify(["首页", "作品集", "服务项目", "合作流程", "关于我们", "在线预约", "联系方式"]),
        packageName: "Pro",
        timeline: "10 天",
        testimonial: "官网的视觉效果完全超出了我们的预期，作品展示效果非常好。现在大部分商业客户都是通过官网了解并预约的。",
        testimonialAuthor: "张摄影师，光影视界创始人",
        featured: false,
        sortOrder: 15,
        designConfig: JSON.stringify({
          style: "creative-minimal",
          primary: "#18181B",
          secondary: "#71717A",
          accent: "#E11D48",
          background: "#FAFAFA",
          surface: "#FFFFFF",
          text: "#18181B",
          muted: "#A1A1AA",
          gradient: "linear-gradient(135deg, #18181B 0%, #27272A 100%)",
          fontDisplay: "'Inter', 'Helvetica Neue', sans-serif",
          fontBody: "'Inter', 'Noto Sans SC', sans-serif",
          borderRadius: "4px",
          heroStyle: "full-screen-minimal",
          cardStyle: "minimal-grid",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1471341971476-ae15ff5dd4ea?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：公益组织 ====================
    prisma.case.create({
      data: {
        slug: "nonprofit-org",
        title: "绿芽基金会：公益组织官网",
        industry: "公益组织",
        tags: JSON.stringify(["公益品牌", "项目展示", "捐赠入口", "志愿者招募"]),
        clientName: "绿芽基金会",
        background: "绿芽基金会是一家专注于乡村教育的公益组织，通过资助乡村学校改善教育环境。需要一个能够展示公益项目、传递品牌价值，并支持捐赠和志愿者招募的官网。",
        challenge: "公益组织需要传递温暖、可信赖的形象，同时要清晰展示项目成果和资金使用情况。需要支持在线捐赠和志愿者报名功能。预算有限，需要高性价比的解决方案。",
        solution: "采用 Pro 套餐，设计风格温暖明亮，传递公益的正能量。首页用故事和数据展示项目影响力，项目页详细介绍每个公益项目，捐赠页清晰展示资金用途。志愿者招募支持在线报名。",
        result: "12 天完成交付。官网上线后月均捐赠额增长 150%，志愿者报名量增长 300%。官网成为品牌传播和筹款的重要渠道。",
        pages: JSON.stringify(["首页", "关于我们", "公益项目", "项目成果", "捐赠支持", "志愿者招募", "新闻动态", "联系我们"]),
        packageName: "Pro",
        timeline: "12 天",
        testimonial: "官网很好地传递了我们的公益理念，捐赠和志愿者报名都很方便。现在更多人通过官网了解并支持我们的项目。",
        testimonialAuthor: "林秘书长，绿芽基金会",
        featured: false,
        sortOrder: 16,
        designConfig: JSON.stringify({
          style: "compassionate",
          primary: "#059669",
          secondary: "#34D399",
          accent: "#10B981",
          background: "#F0FDF4",
          surface: "#FFFFFF",
          text: "#064E3B",
          muted: "#6B7280",
          gradient: "linear-gradient(135deg, #D1FAE5 0%, #A7F3D0 50%, #6EE7B7 100%)",
          fontDisplay: "'Noto Serif SC', 'SimSun', serif",
          fontBody: "'Noto Sans SC', 'PingFang SC', sans-serif",
          borderRadius: "20px",
          heroStyle: "nature-story",
          cardStyle: "soft-organic",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：宠物服务 ====================
    prisma.case.create({
      data: {
        slug: "pet-service",
        title: "萌宠乐园：宠物综合服务中心官网",
        industry: "宠物服务",
        tags: JSON.stringify(["宠物服务", "在线预约", "服务展示", "温馨设计"]),
        clientName: "萌宠乐园",
        background: "萌宠乐园是一家集宠物美容、寄养、医疗为一体的综合服务中心，拥有 5 家门店。需要一个能够展示服务项目、门店环境，并支持在线预约的官网。",
        challenge: "宠物服务需要传递温馨、专业的形象，让宠物主人感到放心。服务项目丰富，需要清晰的分类展示。预约系统需要支持按门店、服务类型、时间段筛选。",
        solution: "采用 Pro 套餐，设计风格温馨可爱，突出对宠物的关爱。首页用萌宠图片吸引眼球，服务页按类别详细展示，门店页展示环境和设施。预约系统支持多维度筛选。",
        result: "11 天完成交付。官网上线后月均预约量增长 200%，新客到店率提升 65%。官网成为品牌传播和获客的重要渠道。",
        pages: JSON.stringify(["首页", "服务项目", "门店环境", "医生团队", "会员服务", "关于我们", "在线预约"]),
        packageName: "Pro",
        timeline: "11 天",
        testimonial: "官网的设计风格很温馨，完全符合宠物服务的调性。预约系统很方便，宠物主人反馈很好。",
        testimonialAuthor: "张店长，萌宠乐园运营经理",
        featured: false,
        sortOrder: 17,
        designConfig: JSON.stringify({
          style: "playful-cute",
          primary: "#EC4899",
          secondary: "#F472B6",
          accent: "#A855F7",
          background: "#FDF2F8",
          surface: "#FFFFFF",
          text: "#1F2937",
          muted: "#9CA3AF",
          gradient: "linear-gradient(135deg, #FCE7F3 0%, #FBCFE8 50%, #F9A8D4 100%)",
          fontDisplay: "'Nunito', 'Comic Neue', sans-serif",
          fontBody: "'Noto Sans SC', 'PingFang SC', sans-serif",
          borderRadius: "24px",
          heroStyle: "playful-blobs",
          cardStyle: "rounded-playful",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 新增案例：汽车服务 ====================
    prisma.case.create({
      data: {
        slug: "auto-service",
        title: "极速养车：汽车养护连锁品牌官网",
        industry: "汽车服务",
        tags: JSON.stringify(["汽车服务", "门店查询", "在线预约", "服务展示"]),
        clientName: "极速养车",
        background: "极速养车是一家汽车养护连锁品牌，提供保养、维修、美容等服务，拥有 40+ 门店。需要一个能够展示服务项目、门店网络，并支持在线预约的官网。",
        challenge: "汽车服务需要传递专业、可靠的形象，让车主感到放心。服务项目丰富，需要清晰的分类展示。门店网络庞大，需要支持地图查询和就近门店推荐。",
        solution: "采用 Pro 套餐，设计风格简约专业，突出汽车养护的专业性。首页用数据和案例展示实力，服务页按类别详细展示，门店页支持地图查询和就近推荐。预约系统支持按门店、服务、时间段筛选。",
        result: "12 天完成交付。官网上线后月均预约量增长 180%，新客到店率提升 60%。官网成为品牌传播和获客的重要渠道。",
        pages: JSON.stringify(["首页", "服务项目", "门店查询", "品质保障", "会员服务", "关于我们", "在线预约"]),
        packageName: "Pro",
        timeline: "12 天",
        testimonial: "官网的专业度得到了车主的一致好评，预约量增长明显。特别是门店查询功能，帮助车主快速找到最近的门店。",
        testimonialAuthor: "王经理，极速养车品牌总监",
        featured: false,
        sortOrder: 18,
        designConfig: JSON.stringify({
          style: "tech-automotive",
          primary: "#0EA5E9",
          secondary: "#0284C7",
          accent: "#38BDF8",
          background: "#F0F9FF",
          surface: "#FFFFFF",
          text: "#0C4A6E",
          muted: "#64748B",
          gradient: "linear-gradient(135deg, #E0F2FE 0%, #BAE6FD 50%, #7DD3FC 100%)",
          fontDisplay: "'Roboto Condensed', 'Oswald', sans-serif",
          fontBody: "'Roboto', 'Noto Sans SC', sans-serif",
          borderRadius: "8px",
          heroStyle: "tech-split",
          cardStyle: "clean-functional",
        }),
        images: JSON.stringify({"hero": "https://images.unsplash.com/photo-1625047509248-ec889cbff17f?w=1200&h=600&fit=crop", "gallery": ["https://images.unsplash.com/photo-1625047509248-ec889cbff17f?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&h=400&fit=crop", "https://images.unsplash.com/photo-1507136566006-cfc505b114fc?w=600&h=400&fit=crop"]}),
      },
    }),
    // ==================== 案例：韶域文化环 ====================
    prisma.case.create({
      data: {
        slug: "shaoyu-cultural-ring",
        title: "韶域文化环：数智共生赋能粤北非遗活态传承",
        industry: "文化教育",
        tags: JSON.stringify(["AIGC", "微信小程序", "AR文化卡片", "知识图谱", "非遗传承", "乡村振兴", "百千万工程", "新文工交叉", "跨文化传播", "数字人", "丹霞地貌", "瑶绣"]),
        clientName: "广东技术师范大学国际教育学院",
        background: "韶域文化环是由广东技术师范大学国际教育学院\"文脉传承\"大学生突击队发起的创新项目，以\"数智共生\"为核心理念，聚焦粤北韶关非遗文化的数字化保护与国际化传播。项目作为广东省\"百千万工程\"突击队行动重点实践项目，由傅熠婷担任负责人，团队涵盖会计学、计算机科学与技术、教育技术学等多学科背景成员。项目采用\"线上交流+线下互动+文化传递\"三大模块闭环设计，通过\"文脉传承\"微信小程序、AR文化卡片、双语文化数据库等数字产品，将瑶绣（2011年列入第三批国家级非遗，项目编号Ⅶ-105）、客家山歌、采茶戏、珠玑姓氏迁徙、丹霞地貌（2010年列入《世界遗产名录》）等文化资源进行系统性数字化整合。2025年7月，团队深入南雄珠玑镇开展为期15天（含7天线下集中）的暑期社会实践，累计回收有效问卷200份、完成深度访谈50人，记录了瑶绣、茶则等非遗技艺与民俗文化。2026年，项目升级为\"数智共生：新文工交叉下韶关非遗AIGC活态传承研究\"，入选广东大学生科技创新培育项目，获得10000元资助，研究周期2026年4月至2027年3月。",
        challenge: "粤北韶关拥有21项非遗项目（其中国家级3项：瑶族盘王节、瑶族刺绣、瑶族民歌）和33位非遗传承人，但面临四重结构性困境：一是传承人老龄化严重，\"人走艺失\"风险迫在眉睫；二是年轻一代认知断层，留学生文化传播中48%存在信息误读；三是传播渠道单一，传统方式难以触达Z世代受众；四是资源散落化，缺乏系统性数字档案。作为大学生创业项目，还需要在有限预算（10000元资助金）内实现AIGC、知识图谱、数字人等前沿技术的工程化落地，并解决AR扫码\"单向展示\"、内容人工采编效率低、跨语种传播成本高、活动后留存率不足25%等一期项目暴露出的结构性瓶颈。",
        solution: "项目采用\"1-1-3-5-1\"整体架构：一图谱（韶关非遗多模态文化知识图谱，基于Neo4j+向量数据库，预计抽取实体3000+、关系2万+）；一大模型（基于Qwen2.5-7B/DeepSeek-V3-Lite/GLM-4-9B开源底座，通过LoRA/QLoRA微调生成Shao-Culture-LLM垂域模型，支持本地化部署）；三智能体（非遗传承人数字分身Shao-Master、文化共学Shao-Tutor、文化创作Shao-Creator）；五场景（校园沉浸式非遗课堂、乡村文化振兴驿站、跨境青年文化直播间、数字文旅融合体验区、数字文化展陈与文创电商）；一评估（非遗活态传承数字化评估标准V1.0）。技术栈涵盖AIGC文生图/视频/3D、语音克隆、AR/动态二维码、LangGraph+AutoGen+Dify智能体编排、Stable Diffusion 3.5+ControlNet纹样生成等。设计风格融合传统中国美学与现代数字感，以\"前期准备—现场实践—总结提升\"为主线推进项目落地。",
        result: "项目取得丰硕成果：一是政策认可——入选广东省\"百千万工程\"突击队行动、广东大学生科技创新培育项目（2026年立项），获第十四届\"赢在广州\"大学生创业大赛校赛二等奖；二是学术产出——完成《广东技术师范大学\"文脉传承\"突击队南雄市实践报告》《研习南粤项目成果报告》《珠玑镇高质量发展专题采访》等多份实践报告，在省级期刊发表学术论文2篇；三是技术成果——建成包含500+文化符号的双语文化数据库，开发\"文脉传承\"小程序与AR文化卡片礼盒，申报2项实用新型专利（AR卡片结构设计）；四是社会影响——文化传播链触达8国民众，东南亚核心区覆盖率达73%，线下活动参与者文化认同感提升37%，韶关学生方言课堂后发言率提升30%，培养12名持证双语文化讲解员；五是产业对接——已与韶关文旅局达成非遗IP转化意向，与韶关市特殊教育学校合作开展手语版文化小卡试点。项目获韶关市中职学校表扬信、韶关市特殊教育学校表扬信、南雄市乡村振兴实战赛政府代言人授权书等荣誉认证。",
        pages: JSON.stringify(["首页", "项目介绍", "文化地图", "实践成果", "团队故事", "联系我们"]),
        packageName: "Starter",
        timeline: "15 天",
        testimonial: "作为大学生项目，我们预算有限但要求不低。官网完美呈现了我们的文化理念和技术实力，帮助我们在省级评审中脱颖而出。从珠玑古巷的历史底蕴到瑶绣的非遗魅力，官网让外界看到了南雄的文化之美。项目「数智共生」的理念和「1-1-3-5-1」的技术架构，在官网上得到了专业而生动的呈现。",
        testimonialAuthor: "傅熠婷，项目负责人，广东技术师范大学国际教育学院",
        featured: true,
        sortOrder: 19,
        designConfig: JSON.stringify({
          style: "cultural-heritage",
          primary: "#1B5E20",
          secondary: "#4E342E",
          accent: "#BF360C",
          background: "#F1F8E9",
          surface: "#FFFFFF",
          text: "#1B1B1B",
          muted: "#5D4037",
          gradient: "linear-gradient(135deg, #1B5E20 0%, #4E342E 50%, #BF360C 100%)",
          fontDisplay: "'Noto Serif SC', 'SimSun', serif",
          fontBody: "'Noto Sans SC', 'PingFang SC', sans-serif",
          borderRadius: "12px",
          heroStyle: "cultural-overlay",
          cardStyle: "heritage-cards",
        }),
        images: JSON.stringify({
          hero: "/cases/shaoyu/danxiashan.jpg",
          gallery: [
            { src: "/cases/shaoyu/丹霞山阳元石.jpg", caption: "丹霞山阳元石——2010年列入《世界遗产名录》，世界自然遗产", category: "文化地标" },
            { src: "/cases/shaoyu/chuanding.jpg", caption: "船底顶——粤北最高峰，丹霞地貌与高山草甸的完美结合", category: "文化地标" },
            { src: "/cases/shaoyu/nanxiong-view.jpg", caption: "南雄珠玑镇全景——广府人的发祥地，千年古驿道的起点", category: "文化地标" },
            { src: "/cases/shaoyu/nanshansi.jpg", caption: "南山寺——韶关千年古刹，佛教文化与岭南建筑的交融", category: "文化地标" },
            { src: "/cases/shaoyu/zhugu-xiang.jpg", caption: "珠玑古巷——广府文化根脉所在，姓氏迁徙的历史见证", category: "文化地标" },
            { src: "/cases/shaoyu/瑶绣 百褶之裙.jpg", caption: "瑶绣「百褶之裙」——国家级非遗项目（编号Ⅶ-105），瑶族女性智慧的结晶", category: "非遗技艺" },
            { src: "/cases/shaoyu/yaoxiu-detail.jpg", caption: "瑶绣针法细节——五色丝线交织，每针每线承载民族记忆", category: "非遗技艺" },
            { src: "/cases/shaoyu/yaoxiu-zhenfa.png", caption: "瑶绣传统针法图解——反面刺绣正面看，技法独特闻名于世", category: "非遗技艺" },
            { src: "/cases/shaoyu/yaozu-dress.jpg", caption: "瑶族传统服饰——色彩斑斓的民族符号，绣娘指尖的艺术", category: "非遗技艺" },
            { src: "/cases/shaoyu/茶则.jpg", caption: "韶关传统茶则——茶道器具中的匠心传承", category: "非遗技艺" },
            { src: "/cases/shaoyu/wenmai-chuan.jpg", caption: "「文脉传承」团队标识——以技术守护文化根脉", category: "团队实践" },
            { src: "/cases/shaoyu/team-activity.jpg", caption: "团队在南雄珠玑镇开展田野调查——入户访谈记录非遗技艺", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-1.jpg", caption: "文脉传承突击队全体成员——跨学科协作的文化守护者", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-2.jpg", caption: "团队深入瑶族村寨——与传承人面对面交流", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-3.jpg", caption: "田野调查现场——记录珠玑古巷的历史故事", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-4.jpg", caption: "团队在灵潭村调研——探访绿美乡村建设成果", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-5.jpg", caption: "入户访谈交流——倾听村民对文化传承的期望", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-6.jpg", caption: "团队合影留念——青春赋能·筑梦南雄", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-7.jpg", caption: "团队在丹霞山实地考察——记录地质人文资源", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-8.jpg", caption: "团队讨论项目方案——从数据到模型的规划", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-9.jpg", caption: "团队整理调研资料——200份问卷+50人深度访谈", category: "团队实践" },
            { src: "/cases/shaoyu/team-photo-10.jpg", caption: "团队总结复盘——把一线记录整理成可复用的活动包", category: "团队实践" },
            { src: "/cases/shaoyu/cultural-exchange.jpg", caption: "跨文化交流活动——留学生体验瑶绣技艺", category: "活动成果" },
            { src: "/cases/shaoyu/fieldwork.jpg", caption: "田野调查记录——数字化采集非遗技艺影像", category: "活动成果" },
            { src: "/cases/shaoyu/classroom.jpg", caption: "英语创新课堂——用双语讲述韶关文化故事", category: "活动成果" },
            { src: "/cases/shaoyu/miniprogram-demo.jpg", caption: "「文脉传承」小程序——学习打卡+瑶绣设计权限激励", category: "数字产品" },
            { src: "/cases/shaoyu/ar-card.jpg", caption: "AR文化卡片礼盒——扫码即可呈现丹霞地貌实景", category: "数字产品" },
            { src: "/cases/shaoyu/cultural-card.jpg", caption: "双语文化小卡——中英文对照+动态二维码视频解说", category: "数字产品" },
            { src: "/cases/shaoyu/yaoxiu-pattern.jpg", caption: "瑶绣纹样数据库——收录500+文化符号的双语数据库", category: "数字产品" },
            { src: "/cases/shaoyu/mindmap.png", caption: "项目架构思维导图——「一图谱·一大模型·三智能体·五场景·一评估」", category: "项目规划" },
            { src: "/cases/shaoyu/wechat-4.png", caption: "荣誉认证——韶关市中职学校表扬信", category: "荣誉认证" },
            { src: "/cases/shaoyu/wechat-5.png", caption: "荣誉认证——韶关市特殊教育学校表扬信", category: "荣誉认证" },
            { src: "/cases/shaoyu/wechat-6.png", caption: "荣誉认证——南雄市乡村振兴实战赛政府代言人授权书", category: "荣誉认证" },
            { src: "/cases/shaoyu/gouweizhang.jpg", caption: "狗尾嶂——韶关自然生态资源，生物多样性保护", category: "自然生态" },
            { src: "/cases/shaoyu/baixiang.jpg", caption: "白鹇——广东省省鸟，韶关山林中的精灵", category: "自然生态" },
            { src: "/cases/shaoyu/chuanshanjia.jpg", caption: "穿山甲——韶关珍稀野生动物，生态保护的见证", category: "自然生态" },
            { src: "/cases/shaoyu/huananhu.jpg", caption: "华南虎——韶关历史上的珍稀物种，生态修复的目标", category: "自然生态" },
            { src: "/cases/shaoyu/yunbao.jpg", caption: "云豹——粤北山区的顶级捕食者，生态链的关键", category: "自然生态" },
          ],
        }),
        mediaReports: JSON.stringify([
          {
            source: "中国网",
            title: "广东技术师范大学「文脉传承」突击队以技术赋能文化传承，创新英语课堂焕发南雄学子自信",
            url: "http://gx.china.com.cn/2025-07/22/content_43180822.html",
            date: "2025-07-22",
          },
          {
            source: "中教网",
            title: "古道上倾听·光影间赋能——广师大青年学子南雄探寻文化传承新路",
            url: "https://www.jyrmt.com/edu/2025/0719/75013.html",
            date: "2025-07-19",
          },
          {
            source: "南雄市政府官网",
            title: "广东技术师范大学青年大学生「百千万工程」突击队与珠玑镇政府结对赋能乡村振兴",
            url: "https://www.gdnx.gov.cn/xwdt/zjdt/content/post_2764729.html",
            date: "2025-07-20",
          },
          {
            source: "大学生云报",
            title: "三下乡|古道上倾听·光影间赋能——广师大青年学子南雄探寻文化传承新路",
            url: "https://www.dxsyb.com/paper/2025/0719/732238.html?t=2553",
            date: "2025-07-19",
          },
          {
            source: "科教在线",
            title: "广师大「文脉传承」突击队：技术赋能文化传承，创新英语课堂焕发南雄学子自信",
            url: "https://www.kjjyzx.com/chn/2025/0720/46663.html",
            date: "2025-07-20",
          },
          {
            source: "长江网",
            title: "广师大学子走进珠玑古巷 解码千年文脉传承新启示",
            url: "http://cjtt.cjn.cn/#/cjttArticleDetail?informationId=4857439&sourceType=0",
            date: "2025-07-21",
          },
        ]),
      },
    }),
  ]);

  console.log(`已创建 ${cases.length} 个案例`);

  // ==================== ActivityLog ====================
  const activityLogs = await Promise.all([
    // 星图智能项目活动
    prisma.activityLog.create({
      data: {
        projectId: projects[0].id,
        type: "status_change",
        content: "项目状态变更为：策划中",
        author: "系统",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[0].id,
        type: "comment",
        content: "客户确认了首页的设计方向，要求突出 AI 写作的核心卖点",
        author: "设计师",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[0].id,
        type: "file_upload",
        content: "上传了首页设计稿 v1",
        author: "设计师",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[0].id,
        type: "revision",
        content: "第 1 轮修改：调整了定价页的布局，增加了功能对比表",
        author: "客户",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[0].id,
        type: "status_change",
        content: "项目状态变更为：已上线",
        author: "系统",
      },
    }),
    // 睿信财务项目活动
    prisma.activityLog.create({
      data: {
        projectId: projects[1].id,
        type: "status_change",
        content: "项目状态变更为：设计中",
        author: "系统",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[1].id,
        type: "comment",
        content: "客户希望整体风格偏稳重专业，参考了竞品的配色方案",
        author: "设计师",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[1].id,
        type: "file_upload",
        content: "上传了全站设计稿",
        author: "设计师",
      },
    }),
    // 极客学院项目活动
    prisma.activityLog.create({
      data: {
        projectId: projects[2].id,
        type: "status_change",
        content: "项目状态变更为：维护中",
        author: "系统",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[2].id,
        type: "comment",
        content: "已完成本月维护：更新了 3 门新课程信息，修复了移动端表单问题",
        author: "维护团队",
      },
    }),
    // 鑫达精密项目活动
    prisma.activityLog.create({
      data: {
        projectId: projects[4].id,
        type: "status_change",
        content: "项目状态变更为：审核中",
        author: "系统",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[4].id,
        type: "comment",
        content: "中英文双语版本已完成，等待客户最终确认",
        author: "开发团队",
      },
    }),
    // 云谷科技园项目活动
    prisma.activityLog.create({
      data: {
        projectId: projects[5].id,
        type: "status_change",
        content: "项目状态变更为：开发中",
        author: "系统",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[5].id,
        type: "file_upload",
        content: "上传了园区 360° 全景素材",
        author: "客户",
      },
    }),
    prisma.activityLog.create({
      data: {
        projectId: projects[5].id,
        type: "comment",
        content: "正在整合 360° 全景展示功能，预计本周完成",
        author: "开发团队",
      },
    }),
  ]);

  console.log(`已创建 ${activityLogs.length} 条活动日志`);

  console.log("\n✅ 种子数据创建完成！");
  console.log(`   联系提交: ${submissions.length} 条`);
  console.log(`   项目: ${projects.length} 条`);
  console.log(`   模板: ${templates.length} 条`);
  console.log(`   维护计划: ${maintenancePlans.length} 条`);
  console.log(`   案例: ${cases.length} 条`);
  console.log(`   活动日志: ${activityLogs.length} 条`);
}

main()
  .catch((e) => {
    console.error("种子数据创建失败:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
